--- 
hotkeys: 
    - 
        action: 
            location: 
                horizontal: center
                vertical: center
        keys: 
            - window
            - 5
        name: Center
    - 
        action: 
            location: 
                horizontal: left
                vertical: center
        keys: 
            - window
            - 4
        name: Left
    - 
        action: 
            location: 
                horizontal: right
                vertical: center
        keys: 
            - window
            - 6
        name: Right
    - 
        action: 
            location: 
                horizontal: center
                vertical: top
        keys: 
            - window
            - 8
        name: Top
    - 
        action: 
            location: 
                horizontal: center
                vertical: bottom
        keys: 
            - window
            - 2
        name: Bottom
    - 
        action: 
            location: 
                horizontal: left
                vertical: top
        keys: 
            - window
            - 7
        name: Top_Left
    - 
        action: 
            location: 
                horizontal: right
                vertical: top
        keys: 
            - window
            - 9
        name: Top_Right
    - 
        action: 
            location: 
                horizontal: left
                vertical: bottom
        keys: 
            - window
            - 1
        name: Bottom_Left
    - 
        action: 
            location: 
                horizontal: right
                vertical: bottom
        keys: 
            - window
            - 3
        name: Bottom_Right
    - 
        action: 
            location: 
                horizontal: center
                vertical: center
            size: 
                height: 100
                width: 50
        keys: 
            - window
            - ctrl
            - 5
        name: Center_Resize_50
    - 
        action: 
            location: 
                horizontal: center
                vertical: center
            size: 
                height: 100
                width: 60
        keys: 
            - window
            - alt
            - 5
        name: Center_Resize_60
    - 
        action: 
            location: 
                horizontal: left
                vertical: center
            size: 
                height: 100
                width: 25
        keys: 
            - window
            - ctrl
            - 4
        name: Left_Resize_25
    - 
        action: 
            location: 
                horizontal: left
                vertical: center
            size: 
                height: 100
                width: 20
        keys: 
            - window
            - alt
            - 4
        name: Left_Resize_20
    - 
        action: 
            location: 
                horizontal: right
                vertical: center
            size: 
                height: 100
                width: 25
        keys: 
            - window
            - ctrl
            - 6
        name: Right_Resize_25
    - 
        action: 
            location: 
                horizontal: right
                vertical: center
            size: 
                height: 100
                width: 20
        keys: 
            - window
            - alt
            - 6
        name: Right_Resize_20
    - 
        action: 
            location: 
                horizontal: left
                vertical: top
            size: 
                height: 50
                width: 25
        keys: 
            - window
            - ctrl
            - 7
        name: Top_Left_Resize
    - 
        action: 
            location: 
                horizontal: right
                vertical: top
            size: 
                height: 50
                width: 25
        keys: 
            - window
            - ctrl
            - 9
        name: Top_Right_Resize
    - 
        action: 
            location: 
                horizontal: left
                vertical: bottom
            size: 
                height: 50
                width: 25
        keys: 
            - window
            - ctrl
            - 1
        name: Bottom_Left_Resize
    - 
        action: 
            location: 
                horizontal: right
                vertical: bottom
            size: 
                height: 50
                width: 25
        keys: 
            - window
            - ctrl
            - 3
        name: Bottom_Right_Resize
    - 
        action: 
            location: 
                horizontal: center
                vertical: top
            size: 
                height: 50
                width: 50
        keys: 
            - window
            - ctrl
            - 8
        name: Top_Resize_50
    - 
        action: 
            location: 
                horizontal: center
                vertical: bottom
            size: 
                height: 50
                width: 50
        keys: 
            - window
            - ctrl
            - 2
        name: Bottom_Resize_50
    