#pragma once

#include "wx-3.1/wx/defs.h"

#include <map>
#include <string>

//=====================================================================================================================

namespace wm::keys
{
    inline const std::map<std::string, wxKeyCode> keyMap = {{"a", wxKeyCode::WXK_CONTROL_A},
                                                            {"b", wxKeyCode::WXK_CONTROL_B},
                                                            {"c", wxKeyCode::WXK_CONTROL_C},
                                                            {"d", wxKeyCode::WXK_CONTROL_D},
                                                            {"e", wxKeyCode::WXK_CONTROL_E},
                                                            {"f", wxKeyCode::WXK_CONTROL_F},
                                                            {"g", wxKeyCode::WXK_CONTROL_G},
                                                            {"h", wxKeyCode::WXK_CONTROL_H},
                                                            {"i", wxKeyCode::WXK_CONTROL_I},
                                                            {"j", wxKeyCode::WXK_CONTROL_J},
                                                            {"k", wxKeyCode::WXK_CONTROL_K},
                                                            {"l", wxKeyCode::WXK_CONTROL_L},
                                                            {"m", wxKeyCode::WXK_CONTROL_M},
                                                            {"n", wxKeyCode::WXK_CONTROL_N},
                                                            {"o", wxKeyCode::WXK_CONTROL_O},
                                                            {"p", wxKeyCode::WXK_CONTROL_P},
                                                            {"q", wxKeyCode::WXK_CONTROL_Q},
                                                            {"r", wxKeyCode::WXK_CONTROL_R},
                                                            {"s", wxKeyCode::WXK_CONTROL_S},
                                                            {"t", wxKeyCode::WXK_CONTROL_T},
                                                            {"u", wxKeyCode::WXK_CONTROL_U},
                                                            {"v", wxKeyCode::WXK_CONTROL_V},
                                                            {"w", wxKeyCode::WXK_CONTROL_W},
                                                            {"x", wxKeyCode::WXK_CONTROL_X},
                                                            {"y", wxKeyCode::WXK_CONTROL_Y},
                                                            {"z", wxKeyCode::WXK_CONTROL_Z},
                                                            {"backspace", wxKeyCode::WXK_BACK},
                                                            {"tab", wxKeyCode::WXK_TAB},
                                                            {"return", wxKeyCode::WXK_RETURN},
                                                            {"esc", wxKeyCode::WXK_ESCAPE},
                                                            {"space", wxKeyCode::WXK_SPACE},
                                                            {"delete", wxKeyCode::WXK_DELETE},
                                                            {"shift", wxKeyCode::WXK_SHIFT},
                                                            {"alt", wxKeyCode::WXK_ALT},
                                                            {"ctrl", wxKeyCode::WXK_CONTROL},
                                                            {"menu", wxKeyCode::WXK_MENU},
                                                            {"end", wxKeyCode::WXK_END},
                                                            {"home", wxKeyCode::WXK_HOME},
                                                            {"left", wxKeyCode::WXK_LEFT},
                                                            {"up", wxKeyCode::WXK_UP},
                                                            {"right", wxKeyCode::WXK_RIGHT},
                                                            {"down", wxKeyCode::WXK_DOWN},
                                                            {"insert", wxKeyCode::WXK_INSERT},
                                                            {"0", wxKeyCode::WXK_NUMPAD0},
                                                            {"1", wxKeyCode::WXK_NUMPAD1},
                                                            {"2", wxKeyCode::WXK_NUMPAD2},
                                                            {"3", wxKeyCode::WXK_NUMPAD3},
                                                            {"4", wxKeyCode::WXK_NUMPAD4},
                                                            {"5", wxKeyCode::WXK_NUMPAD5},
                                                            {"6", wxKeyCode::WXK_NUMPAD6},
                                                            {"7", wxKeyCode::WXK_NUMPAD7},
                                                            {"8", wxKeyCode::WXK_NUMPAD8},
                                                            {"9", wxKeyCode::WXK_NUMPAD9},
                                                            {"+", wxKeyCode::WXK_ADD},
                                                            {"-", wxKeyCode::WXK_SUBTRACT},
                                                            {"*", wxKeyCode::WXK_MULTIPLY},
                                                            {"/", wxKeyCode::WXK_DIVIDE},
                                                            {"decimal", wxKeyCode::WXK_DECIMAL},
                                                            {"numlock", wxKeyCode::WXK_NUMLOCK},
                                                            {"f1", wxKeyCode::WXK_F1},
                                                            {"f2", wxKeyCode::WXK_F2},
                                                            {"f3", wxKeyCode::WXK_F3},
                                                            {"f4", wxKeyCode::WXK_F4},
                                                            {"f5", wxKeyCode::WXK_F5},
                                                            {"f6", wxKeyCode::WXK_F6},
                                                            {"f7", wxKeyCode::WXK_F7},
                                                            {"f8", wxKeyCode::WXK_F8},
                                                            {"f9", wxKeyCode::WXK_F9},
                                                            {"f10", wxKeyCode::WXK_F10},
                                                            {"f11", wxKeyCode::WXK_F11},
                                                            {"f12", wxKeyCode::WXK_F12},
                                                            {"pageup", wxKeyCode::WXK_PAGEUP},
                                                            {"pagedown", wxKeyCode::WXK_PAGEDOWN},
                                                            {"window", wxKeyCode::WXK_WINDOWS_LEFT}};
}
